export enum PATH {
  HOME = 'home',
  RESIDENTE_LISTA = 'residente-lista',
  RESIDENTE_CREAR = 'residente-crear',
  RESIDENTE_DETALLE = 'residente-detalle',
  SERVICIO_LISTA = 'servicio-lista',
  SERVICIO_CREAR = 'servicio-crear',
  SERVICIO_DETALLE = 'servicio-detalle',
  RESERVA_LISTA = 'reserva-lista',
  RESERVA_CREAR = 'reserva-crear',
  RESERVA_DETALLE = 'reserva-detalle',
  LOGIN = 'login',
  OLVIDO_CONTRASENA = 'olvido-contrasena',
  REGISTRO = 'registro',
}
